# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.24

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /opt/homebrew/Cellar/cmake/3.24.0/bin/cmake

# The command to remove a file.
RM = /opt/homebrew/Cellar/cmake/3.24.0/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/olgaborisova/Desktop/git_webserv

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/olgaborisova/Desktop/git_webserv

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/opt/homebrew/Cellar/cmake/3.24.0/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/opt/homebrew/Cellar/cmake/3.24.0/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/olgaborisova/Desktop/git_webserv/CMakeFiles /Users/olgaborisova/Desktop/git_webserv//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/olgaborisova/Desktop/git_webserv/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named web-server

# Build rule for target.
web-server: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 web-server
.PHONY : web-server

# fast build rule for target.
web-server/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/web-server.dir/build.make CMakeFiles/web-server.dir/build
.PHONY : web-server/fast

srcs/cgi/SingleCgiHandler.o: srcs/cgi/SingleCgiHandler.cpp.o
.PHONY : srcs/cgi/SingleCgiHandler.o

# target to build an object file
srcs/cgi/SingleCgiHandler.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/web-server.dir/build.make CMakeFiles/web-server.dir/srcs/cgi/SingleCgiHandler.cpp.o
.PHONY : srcs/cgi/SingleCgiHandler.cpp.o

srcs/cgi/SingleCgiHandler.i: srcs/cgi/SingleCgiHandler.cpp.i
.PHONY : srcs/cgi/SingleCgiHandler.i

# target to preprocess a source file
srcs/cgi/SingleCgiHandler.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/web-server.dir/build.make CMakeFiles/web-server.dir/srcs/cgi/SingleCgiHandler.cpp.i
.PHONY : srcs/cgi/SingleCgiHandler.cpp.i

srcs/cgi/SingleCgiHandler.s: srcs/cgi/SingleCgiHandler.cpp.s
.PHONY : srcs/cgi/SingleCgiHandler.s

# target to generate assembly for a file
srcs/cgi/SingleCgiHandler.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/web-server.dir/build.make CMakeFiles/web-server.dir/srcs/cgi/SingleCgiHandler.cpp.s
.PHONY : srcs/cgi/SingleCgiHandler.cpp.s

srcs/config/Config.o: srcs/config/Config.cpp.o
.PHONY : srcs/config/Config.o

# target to build an object file
srcs/config/Config.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/web-server.dir/build.make CMakeFiles/web-server.dir/srcs/config/Config.cpp.o
.PHONY : srcs/config/Config.cpp.o

srcs/config/Config.i: srcs/config/Config.cpp.i
.PHONY : srcs/config/Config.i

# target to preprocess a source file
srcs/config/Config.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/web-server.dir/build.make CMakeFiles/web-server.dir/srcs/config/Config.cpp.i
.PHONY : srcs/config/Config.cpp.i

srcs/config/Config.s: srcs/config/Config.cpp.s
.PHONY : srcs/config/Config.s

# target to generate assembly for a file
srcs/config/Config.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/web-server.dir/build.make CMakeFiles/web-server.dir/srcs/config/Config.cpp.s
.PHONY : srcs/config/Config.cpp.s

srcs/core/events/Event.o: srcs/core/events/Event.cpp.o
.PHONY : srcs/core/events/Event.o

# target to build an object file
srcs/core/events/Event.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/web-server.dir/build.make CMakeFiles/web-server.dir/srcs/core/events/Event.cpp.o
.PHONY : srcs/core/events/Event.cpp.o

srcs/core/events/Event.i: srcs/core/events/Event.cpp.i
.PHONY : srcs/core/events/Event.i

# target to preprocess a source file
srcs/core/events/Event.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/web-server.dir/build.make CMakeFiles/web-server.dir/srcs/core/events/Event.cpp.i
.PHONY : srcs/core/events/Event.cpp.i

srcs/core/events/Event.s: srcs/core/events/Event.cpp.s
.PHONY : srcs/core/events/Event.s

# target to generate assembly for a file
srcs/core/events/Event.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/web-server.dir/build.make CMakeFiles/web-server.dir/srcs/core/events/Event.cpp.s
.PHONY : srcs/core/events/Event.cpp.s

srcs/core/events/EventPresets.o: srcs/core/events/EventPresets.cpp.o
.PHONY : srcs/core/events/EventPresets.o

# target to build an object file
srcs/core/events/EventPresets.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/web-server.dir/build.make CMakeFiles/web-server.dir/srcs/core/events/EventPresets.cpp.o
.PHONY : srcs/core/events/EventPresets.cpp.o

srcs/core/events/EventPresets.i: srcs/core/events/EventPresets.cpp.i
.PHONY : srcs/core/events/EventPresets.i

# target to preprocess a source file
srcs/core/events/EventPresets.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/web-server.dir/build.make CMakeFiles/web-server.dir/srcs/core/events/EventPresets.cpp.i
.PHONY : srcs/core/events/EventPresets.cpp.i

srcs/core/events/EventPresets.s: srcs/core/events/EventPresets.cpp.s
.PHONY : srcs/core/events/EventPresets.s

# target to generate assembly for a file
srcs/core/events/EventPresets.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/web-server.dir/build.make CMakeFiles/web-server.dir/srcs/core/events/EventPresets.cpp.s
.PHONY : srcs/core/events/EventPresets.cpp.s

srcs/core/modules/EpollModule.o: srcs/core/modules/EpollModule.cpp.o
.PHONY : srcs/core/modules/EpollModule.o

# target to build an object file
srcs/core/modules/EpollModule.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/web-server.dir/build.make CMakeFiles/web-server.dir/srcs/core/modules/EpollModule.cpp.o
.PHONY : srcs/core/modules/EpollModule.cpp.o

srcs/core/modules/EpollModule.i: srcs/core/modules/EpollModule.cpp.i
.PHONY : srcs/core/modules/EpollModule.i

# target to preprocess a source file
srcs/core/modules/EpollModule.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/web-server.dir/build.make CMakeFiles/web-server.dir/srcs/core/modules/EpollModule.cpp.i
.PHONY : srcs/core/modules/EpollModule.cpp.i

srcs/core/modules/EpollModule.s: srcs/core/modules/EpollModule.cpp.s
.PHONY : srcs/core/modules/EpollModule.s

# target to generate assembly for a file
srcs/core/modules/EpollModule.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/web-server.dir/build.make CMakeFiles/web-server.dir/srcs/core/modules/EpollModule.cpp.s
.PHONY : srcs/core/modules/EpollModule.cpp.s

srcs/core/modules/PollModule.o: srcs/core/modules/PollModule.cpp.o
.PHONY : srcs/core/modules/PollModule.o

# target to build an object file
srcs/core/modules/PollModule.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/web-server.dir/build.make CMakeFiles/web-server.dir/srcs/core/modules/PollModule.cpp.o
.PHONY : srcs/core/modules/PollModule.cpp.o

srcs/core/modules/PollModule.i: srcs/core/modules/PollModule.cpp.i
.PHONY : srcs/core/modules/PollModule.i

# target to preprocess a source file
srcs/core/modules/PollModule.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/web-server.dir/build.make CMakeFiles/web-server.dir/srcs/core/modules/PollModule.cpp.i
.PHONY : srcs/core/modules/PollModule.cpp.i

srcs/core/modules/PollModule.s: srcs/core/modules/PollModule.cpp.s
.PHONY : srcs/core/modules/PollModule.s

# target to generate assembly for a file
srcs/core/modules/PollModule.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/web-server.dir/build.make CMakeFiles/web-server.dir/srcs/core/modules/PollModule.cpp.s
.PHONY : srcs/core/modules/PollModule.cpp.s

srcs/http/HttpModule.o: srcs/http/HttpModule.cpp.o
.PHONY : srcs/http/HttpModule.o

# target to build an object file
srcs/http/HttpModule.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/web-server.dir/build.make CMakeFiles/web-server.dir/srcs/http/HttpModule.cpp.o
.PHONY : srcs/http/HttpModule.cpp.o

srcs/http/HttpModule.i: srcs/http/HttpModule.cpp.i
.PHONY : srcs/http/HttpModule.i

# target to preprocess a source file
srcs/http/HttpModule.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/web-server.dir/build.make CMakeFiles/web-server.dir/srcs/http/HttpModule.cpp.i
.PHONY : srcs/http/HttpModule.cpp.i

srcs/http/HttpModule.s: srcs/http/HttpModule.cpp.s
.PHONY : srcs/http/HttpModule.s

# target to generate assembly for a file
srcs/http/HttpModule.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/web-server.dir/build.make CMakeFiles/web-server.dir/srcs/http/HttpModule.cpp.s
.PHONY : srcs/http/HttpModule.cpp.s

srcs/http/Request.o: srcs/http/Request.cpp.o
.PHONY : srcs/http/Request.o

# target to build an object file
srcs/http/Request.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/web-server.dir/build.make CMakeFiles/web-server.dir/srcs/http/Request.cpp.o
.PHONY : srcs/http/Request.cpp.o

srcs/http/Request.i: srcs/http/Request.cpp.i
.PHONY : srcs/http/Request.i

# target to preprocess a source file
srcs/http/Request.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/web-server.dir/build.make CMakeFiles/web-server.dir/srcs/http/Request.cpp.i
.PHONY : srcs/http/Request.cpp.i

srcs/http/Request.s: srcs/http/Request.cpp.s
.PHONY : srcs/http/Request.s

# target to generate assembly for a file
srcs/http/Request.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/web-server.dir/build.make CMakeFiles/web-server.dir/srcs/http/Request.cpp.s
.PHONY : srcs/http/Request.cpp.s

srcs/http/Response.o: srcs/http/Response.cpp.o
.PHONY : srcs/http/Response.o

# target to build an object file
srcs/http/Response.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/web-server.dir/build.make CMakeFiles/web-server.dir/srcs/http/Response.cpp.o
.PHONY : srcs/http/Response.cpp.o

srcs/http/Response.i: srcs/http/Response.cpp.i
.PHONY : srcs/http/Response.i

# target to preprocess a source file
srcs/http/Response.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/web-server.dir/build.make CMakeFiles/web-server.dir/srcs/http/Response.cpp.i
.PHONY : srcs/http/Response.cpp.i

srcs/http/Response.s: srcs/http/Response.cpp.s
.PHONY : srcs/http/Response.s

# target to generate assembly for a file
srcs/http/Response.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/web-server.dir/build.make CMakeFiles/web-server.dir/srcs/http/Response.cpp.s
.PHONY : srcs/http/Response.cpp.s

srcs/libjtoc/src/ft_atoi.o: srcs/libjtoc/src/ft_atoi.cpp.o
.PHONY : srcs/libjtoc/src/ft_atoi.o

# target to build an object file
srcs/libjtoc/src/ft_atoi.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/web-server.dir/build.make CMakeFiles/web-server.dir/srcs/libjtoc/src/ft_atoi.cpp.o
.PHONY : srcs/libjtoc/src/ft_atoi.cpp.o

srcs/libjtoc/src/ft_atoi.i: srcs/libjtoc/src/ft_atoi.cpp.i
.PHONY : srcs/libjtoc/src/ft_atoi.i

# target to preprocess a source file
srcs/libjtoc/src/ft_atoi.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/web-server.dir/build.make CMakeFiles/web-server.dir/srcs/libjtoc/src/ft_atoi.cpp.i
.PHONY : srcs/libjtoc/src/ft_atoi.cpp.i

srcs/libjtoc/src/ft_atoi.s: srcs/libjtoc/src/ft_atoi.cpp.s
.PHONY : srcs/libjtoc/src/ft_atoi.s

# target to generate assembly for a file
srcs/libjtoc/src/ft_atoi.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/web-server.dir/build.make CMakeFiles/web-server.dir/srcs/libjtoc/src/ft_atoi.cpp.s
.PHONY : srcs/libjtoc/src/ft_atoi.cpp.s

srcs/libjtoc/src/ft_bzero.o: srcs/libjtoc/src/ft_bzero.cpp.o
.PHONY : srcs/libjtoc/src/ft_bzero.o

# target to build an object file
srcs/libjtoc/src/ft_bzero.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/web-server.dir/build.make CMakeFiles/web-server.dir/srcs/libjtoc/src/ft_bzero.cpp.o
.PHONY : srcs/libjtoc/src/ft_bzero.cpp.o

srcs/libjtoc/src/ft_bzero.i: srcs/libjtoc/src/ft_bzero.cpp.i
.PHONY : srcs/libjtoc/src/ft_bzero.i

# target to preprocess a source file
srcs/libjtoc/src/ft_bzero.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/web-server.dir/build.make CMakeFiles/web-server.dir/srcs/libjtoc/src/ft_bzero.cpp.i
.PHONY : srcs/libjtoc/src/ft_bzero.cpp.i

srcs/libjtoc/src/ft_bzero.s: srcs/libjtoc/src/ft_bzero.cpp.s
.PHONY : srcs/libjtoc/src/ft_bzero.s

# target to generate assembly for a file
srcs/libjtoc/src/ft_bzero.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/web-server.dir/build.make CMakeFiles/web-server.dir/srcs/libjtoc/src/ft_bzero.cpp.s
.PHONY : srcs/libjtoc/src/ft_bzero.cpp.s

srcs/libjtoc/src/ft_isdigit.o: srcs/libjtoc/src/ft_isdigit.cpp.o
.PHONY : srcs/libjtoc/src/ft_isdigit.o

# target to build an object file
srcs/libjtoc/src/ft_isdigit.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/web-server.dir/build.make CMakeFiles/web-server.dir/srcs/libjtoc/src/ft_isdigit.cpp.o
.PHONY : srcs/libjtoc/src/ft_isdigit.cpp.o

srcs/libjtoc/src/ft_isdigit.i: srcs/libjtoc/src/ft_isdigit.cpp.i
.PHONY : srcs/libjtoc/src/ft_isdigit.i

# target to preprocess a source file
srcs/libjtoc/src/ft_isdigit.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/web-server.dir/build.make CMakeFiles/web-server.dir/srcs/libjtoc/src/ft_isdigit.cpp.i
.PHONY : srcs/libjtoc/src/ft_isdigit.cpp.i

srcs/libjtoc/src/ft_isdigit.s: srcs/libjtoc/src/ft_isdigit.cpp.s
.PHONY : srcs/libjtoc/src/ft_isdigit.s

# target to generate assembly for a file
srcs/libjtoc/src/ft_isdigit.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/web-server.dir/build.make CMakeFiles/web-server.dir/srcs/libjtoc/src/ft_isdigit.cpp.s
.PHONY : srcs/libjtoc/src/ft_isdigit.cpp.s

srcs/libjtoc/src/ft_itoa.o: srcs/libjtoc/src/ft_itoa.cpp.o
.PHONY : srcs/libjtoc/src/ft_itoa.o

# target to build an object file
srcs/libjtoc/src/ft_itoa.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/web-server.dir/build.make CMakeFiles/web-server.dir/srcs/libjtoc/src/ft_itoa.cpp.o
.PHONY : srcs/libjtoc/src/ft_itoa.cpp.o

srcs/libjtoc/src/ft_itoa.i: srcs/libjtoc/src/ft_itoa.cpp.i
.PHONY : srcs/libjtoc/src/ft_itoa.i

# target to preprocess a source file
srcs/libjtoc/src/ft_itoa.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/web-server.dir/build.make CMakeFiles/web-server.dir/srcs/libjtoc/src/ft_itoa.cpp.i
.PHONY : srcs/libjtoc/src/ft_itoa.cpp.i

srcs/libjtoc/src/ft_itoa.s: srcs/libjtoc/src/ft_itoa.cpp.s
.PHONY : srcs/libjtoc/src/ft_itoa.s

# target to generate assembly for a file
srcs/libjtoc/src/ft_itoa.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/web-server.dir/build.make CMakeFiles/web-server.dir/srcs/libjtoc/src/ft_itoa.cpp.s
.PHONY : srcs/libjtoc/src/ft_itoa.cpp.s

srcs/libjtoc/src/ft_memalloc.o: srcs/libjtoc/src/ft_memalloc.cpp.o
.PHONY : srcs/libjtoc/src/ft_memalloc.o

# target to build an object file
srcs/libjtoc/src/ft_memalloc.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/web-server.dir/build.make CMakeFiles/web-server.dir/srcs/libjtoc/src/ft_memalloc.cpp.o
.PHONY : srcs/libjtoc/src/ft_memalloc.cpp.o

srcs/libjtoc/src/ft_memalloc.i: srcs/libjtoc/src/ft_memalloc.cpp.i
.PHONY : srcs/libjtoc/src/ft_memalloc.i

# target to preprocess a source file
srcs/libjtoc/src/ft_memalloc.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/web-server.dir/build.make CMakeFiles/web-server.dir/srcs/libjtoc/src/ft_memalloc.cpp.i
.PHONY : srcs/libjtoc/src/ft_memalloc.cpp.i

srcs/libjtoc/src/ft_memalloc.s: srcs/libjtoc/src/ft_memalloc.cpp.s
.PHONY : srcs/libjtoc/src/ft_memalloc.s

# target to generate assembly for a file
srcs/libjtoc/src/ft_memalloc.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/web-server.dir/build.make CMakeFiles/web-server.dir/srcs/libjtoc/src/ft_memalloc.cpp.s
.PHONY : srcs/libjtoc/src/ft_memalloc.cpp.s

srcs/libjtoc/src/ft_memcpy.o: srcs/libjtoc/src/ft_memcpy.cpp.o
.PHONY : srcs/libjtoc/src/ft_memcpy.o

# target to build an object file
srcs/libjtoc/src/ft_memcpy.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/web-server.dir/build.make CMakeFiles/web-server.dir/srcs/libjtoc/src/ft_memcpy.cpp.o
.PHONY : srcs/libjtoc/src/ft_memcpy.cpp.o

srcs/libjtoc/src/ft_memcpy.i: srcs/libjtoc/src/ft_memcpy.cpp.i
.PHONY : srcs/libjtoc/src/ft_memcpy.i

# target to preprocess a source file
srcs/libjtoc/src/ft_memcpy.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/web-server.dir/build.make CMakeFiles/web-server.dir/srcs/libjtoc/src/ft_memcpy.cpp.i
.PHONY : srcs/libjtoc/src/ft_memcpy.cpp.i

srcs/libjtoc/src/ft_memcpy.s: srcs/libjtoc/src/ft_memcpy.cpp.s
.PHONY : srcs/libjtoc/src/ft_memcpy.s

# target to generate assembly for a file
srcs/libjtoc/src/ft_memcpy.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/web-server.dir/build.make CMakeFiles/web-server.dir/srcs/libjtoc/src/ft_memcpy.cpp.s
.PHONY : srcs/libjtoc/src/ft_memcpy.cpp.s

srcs/libjtoc/src/ft_strcpy.o: srcs/libjtoc/src/ft_strcpy.cpp.o
.PHONY : srcs/libjtoc/src/ft_strcpy.o

# target to build an object file
srcs/libjtoc/src/ft_strcpy.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/web-server.dir/build.make CMakeFiles/web-server.dir/srcs/libjtoc/src/ft_strcpy.cpp.o
.PHONY : srcs/libjtoc/src/ft_strcpy.cpp.o

srcs/libjtoc/src/ft_strcpy.i: srcs/libjtoc/src/ft_strcpy.cpp.i
.PHONY : srcs/libjtoc/src/ft_strcpy.i

# target to preprocess a source file
srcs/libjtoc/src/ft_strcpy.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/web-server.dir/build.make CMakeFiles/web-server.dir/srcs/libjtoc/src/ft_strcpy.cpp.i
.PHONY : srcs/libjtoc/src/ft_strcpy.cpp.i

srcs/libjtoc/src/ft_strcpy.s: srcs/libjtoc/src/ft_strcpy.cpp.s
.PHONY : srcs/libjtoc/src/ft_strcpy.s

# target to generate assembly for a file
srcs/libjtoc/src/ft_strcpy.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/web-server.dir/build.make CMakeFiles/web-server.dir/srcs/libjtoc/src/ft_strcpy.cpp.s
.PHONY : srcs/libjtoc/src/ft_strcpy.cpp.s

srcs/libjtoc/src/ft_strdup.o: srcs/libjtoc/src/ft_strdup.cpp.o
.PHONY : srcs/libjtoc/src/ft_strdup.o

# target to build an object file
srcs/libjtoc/src/ft_strdup.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/web-server.dir/build.make CMakeFiles/web-server.dir/srcs/libjtoc/src/ft_strdup.cpp.o
.PHONY : srcs/libjtoc/src/ft_strdup.cpp.o

srcs/libjtoc/src/ft_strdup.i: srcs/libjtoc/src/ft_strdup.cpp.i
.PHONY : srcs/libjtoc/src/ft_strdup.i

# target to preprocess a source file
srcs/libjtoc/src/ft_strdup.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/web-server.dir/build.make CMakeFiles/web-server.dir/srcs/libjtoc/src/ft_strdup.cpp.i
.PHONY : srcs/libjtoc/src/ft_strdup.cpp.i

srcs/libjtoc/src/ft_strdup.s: srcs/libjtoc/src/ft_strdup.cpp.s
.PHONY : srcs/libjtoc/src/ft_strdup.s

# target to generate assembly for a file
srcs/libjtoc/src/ft_strdup.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/web-server.dir/build.make CMakeFiles/web-server.dir/srcs/libjtoc/src/ft_strdup.cpp.s
.PHONY : srcs/libjtoc/src/ft_strdup.cpp.s

srcs/libjtoc/src/ft_strhash.o: srcs/libjtoc/src/ft_strhash.cpp.o
.PHONY : srcs/libjtoc/src/ft_strhash.o

# target to build an object file
srcs/libjtoc/src/ft_strhash.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/web-server.dir/build.make CMakeFiles/web-server.dir/srcs/libjtoc/src/ft_strhash.cpp.o
.PHONY : srcs/libjtoc/src/ft_strhash.cpp.o

srcs/libjtoc/src/ft_strhash.i: srcs/libjtoc/src/ft_strhash.cpp.i
.PHONY : srcs/libjtoc/src/ft_strhash.i

# target to preprocess a source file
srcs/libjtoc/src/ft_strhash.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/web-server.dir/build.make CMakeFiles/web-server.dir/srcs/libjtoc/src/ft_strhash.cpp.i
.PHONY : srcs/libjtoc/src/ft_strhash.cpp.i

srcs/libjtoc/src/ft_strhash.s: srcs/libjtoc/src/ft_strhash.cpp.s
.PHONY : srcs/libjtoc/src/ft_strhash.s

# target to generate assembly for a file
srcs/libjtoc/src/ft_strhash.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/web-server.dir/build.make CMakeFiles/web-server.dir/srcs/libjtoc/src/ft_strhash.cpp.s
.PHONY : srcs/libjtoc/src/ft_strhash.cpp.s

srcs/libjtoc/src/ft_strlen.o: srcs/libjtoc/src/ft_strlen.cpp.o
.PHONY : srcs/libjtoc/src/ft_strlen.o

# target to build an object file
srcs/libjtoc/src/ft_strlen.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/web-server.dir/build.make CMakeFiles/web-server.dir/srcs/libjtoc/src/ft_strlen.cpp.o
.PHONY : srcs/libjtoc/src/ft_strlen.cpp.o

srcs/libjtoc/src/ft_strlen.i: srcs/libjtoc/src/ft_strlen.cpp.i
.PHONY : srcs/libjtoc/src/ft_strlen.i

# target to preprocess a source file
srcs/libjtoc/src/ft_strlen.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/web-server.dir/build.make CMakeFiles/web-server.dir/srcs/libjtoc/src/ft_strlen.cpp.i
.PHONY : srcs/libjtoc/src/ft_strlen.cpp.i

srcs/libjtoc/src/ft_strlen.s: srcs/libjtoc/src/ft_strlen.cpp.s
.PHONY : srcs/libjtoc/src/ft_strlen.s

# target to generate assembly for a file
srcs/libjtoc/src/ft_strlen.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/web-server.dir/build.make CMakeFiles/web-server.dir/srcs/libjtoc/src/ft_strlen.cpp.s
.PHONY : srcs/libjtoc/src/ft_strlen.cpp.s

srcs/libjtoc/src/ft_strncmp.o: srcs/libjtoc/src/ft_strncmp.cpp.o
.PHONY : srcs/libjtoc/src/ft_strncmp.o

# target to build an object file
srcs/libjtoc/src/ft_strncmp.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/web-server.dir/build.make CMakeFiles/web-server.dir/srcs/libjtoc/src/ft_strncmp.cpp.o
.PHONY : srcs/libjtoc/src/ft_strncmp.cpp.o

srcs/libjtoc/src/ft_strncmp.i: srcs/libjtoc/src/ft_strncmp.cpp.i
.PHONY : srcs/libjtoc/src/ft_strncmp.i

# target to preprocess a source file
srcs/libjtoc/src/ft_strncmp.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/web-server.dir/build.make CMakeFiles/web-server.dir/srcs/libjtoc/src/ft_strncmp.cpp.i
.PHONY : srcs/libjtoc/src/ft_strncmp.cpp.i

srcs/libjtoc/src/ft_strncmp.s: srcs/libjtoc/src/ft_strncmp.cpp.s
.PHONY : srcs/libjtoc/src/ft_strncmp.s

# target to generate assembly for a file
srcs/libjtoc/src/ft_strncmp.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/web-server.dir/build.make CMakeFiles/web-server.dir/srcs/libjtoc/src/ft_strncmp.cpp.s
.PHONY : srcs/libjtoc/src/ft_strncmp.cpp.s

srcs/libjtoc/src/ft_strnew.o: srcs/libjtoc/src/ft_strnew.cpp.o
.PHONY : srcs/libjtoc/src/ft_strnew.o

# target to build an object file
srcs/libjtoc/src/ft_strnew.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/web-server.dir/build.make CMakeFiles/web-server.dir/srcs/libjtoc/src/ft_strnew.cpp.o
.PHONY : srcs/libjtoc/src/ft_strnew.cpp.o

srcs/libjtoc/src/ft_strnew.i: srcs/libjtoc/src/ft_strnew.cpp.i
.PHONY : srcs/libjtoc/src/ft_strnew.i

# target to preprocess a source file
srcs/libjtoc/src/ft_strnew.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/web-server.dir/build.make CMakeFiles/web-server.dir/srcs/libjtoc/src/ft_strnew.cpp.i
.PHONY : srcs/libjtoc/src/ft_strnew.cpp.i

srcs/libjtoc/src/ft_strnew.s: srcs/libjtoc/src/ft_strnew.cpp.s
.PHONY : srcs/libjtoc/src/ft_strnew.s

# target to generate assembly for a file
srcs/libjtoc/src/ft_strnew.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/web-server.dir/build.make CMakeFiles/web-server.dir/srcs/libjtoc/src/ft_strnew.cpp.s
.PHONY : srcs/libjtoc/src/ft_strnew.cpp.s

srcs/libjtoc/src/ft_strsub.o: srcs/libjtoc/src/ft_strsub.cpp.o
.PHONY : srcs/libjtoc/src/ft_strsub.o

# target to build an object file
srcs/libjtoc/src/ft_strsub.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/web-server.dir/build.make CMakeFiles/web-server.dir/srcs/libjtoc/src/ft_strsub.cpp.o
.PHONY : srcs/libjtoc/src/ft_strsub.cpp.o

srcs/libjtoc/src/ft_strsub.i: srcs/libjtoc/src/ft_strsub.cpp.i
.PHONY : srcs/libjtoc/src/ft_strsub.i

# target to preprocess a source file
srcs/libjtoc/src/ft_strsub.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/web-server.dir/build.make CMakeFiles/web-server.dir/srcs/libjtoc/src/ft_strsub.cpp.i
.PHONY : srcs/libjtoc/src/ft_strsub.cpp.i

srcs/libjtoc/src/ft_strsub.s: srcs/libjtoc/src/ft_strsub.cpp.s
.PHONY : srcs/libjtoc/src/ft_strsub.s

# target to generate assembly for a file
srcs/libjtoc/src/ft_strsub.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/web-server.dir/build.make CMakeFiles/web-server.dir/srcs/libjtoc/src/ft_strsub.cpp.s
.PHONY : srcs/libjtoc/src/ft_strsub.cpp.s

srcs/libjtoc/src/jtoc_get.o: srcs/libjtoc/src/jtoc_get.cpp.o
.PHONY : srcs/libjtoc/src/jtoc_get.o

# target to build an object file
srcs/libjtoc/src/jtoc_get.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/web-server.dir/build.make CMakeFiles/web-server.dir/srcs/libjtoc/src/jtoc_get.cpp.o
.PHONY : srcs/libjtoc/src/jtoc_get.cpp.o

srcs/libjtoc/src/jtoc_get.i: srcs/libjtoc/src/jtoc_get.cpp.i
.PHONY : srcs/libjtoc/src/jtoc_get.i

# target to preprocess a source file
srcs/libjtoc/src/jtoc_get.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/web-server.dir/build.make CMakeFiles/web-server.dir/srcs/libjtoc/src/jtoc_get.cpp.i
.PHONY : srcs/libjtoc/src/jtoc_get.cpp.i

srcs/libjtoc/src/jtoc_get.s: srcs/libjtoc/src/jtoc_get.cpp.s
.PHONY : srcs/libjtoc/src/jtoc_get.s

# target to generate assembly for a file
srcs/libjtoc/src/jtoc_get.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/web-server.dir/build.make CMakeFiles/web-server.dir/srcs/libjtoc/src/jtoc_get.cpp.s
.PHONY : srcs/libjtoc/src/jtoc_get.cpp.s

srcs/libjtoc/src/jtoc_get_raw_data.o: srcs/libjtoc/src/jtoc_get_raw_data.cpp.o
.PHONY : srcs/libjtoc/src/jtoc_get_raw_data.o

# target to build an object file
srcs/libjtoc/src/jtoc_get_raw_data.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/web-server.dir/build.make CMakeFiles/web-server.dir/srcs/libjtoc/src/jtoc_get_raw_data.cpp.o
.PHONY : srcs/libjtoc/src/jtoc_get_raw_data.cpp.o

srcs/libjtoc/src/jtoc_get_raw_data.i: srcs/libjtoc/src/jtoc_get_raw_data.cpp.i
.PHONY : srcs/libjtoc/src/jtoc_get_raw_data.i

# target to preprocess a source file
srcs/libjtoc/src/jtoc_get_raw_data.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/web-server.dir/build.make CMakeFiles/web-server.dir/srcs/libjtoc/src/jtoc_get_raw_data.cpp.i
.PHONY : srcs/libjtoc/src/jtoc_get_raw_data.cpp.i

srcs/libjtoc/src/jtoc_get_raw_data.s: srcs/libjtoc/src/jtoc_get_raw_data.cpp.s
.PHONY : srcs/libjtoc/src/jtoc_get_raw_data.s

# target to generate assembly for a file
srcs/libjtoc/src/jtoc_get_raw_data.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/web-server.dir/build.make CMakeFiles/web-server.dir/srcs/libjtoc/src/jtoc_get_raw_data.cpp.s
.PHONY : srcs/libjtoc/src/jtoc_get_raw_data.cpp.s

srcs/libjtoc/src/jtoc_node.o: srcs/libjtoc/src/jtoc_node.cpp.o
.PHONY : srcs/libjtoc/src/jtoc_node.o

# target to build an object file
srcs/libjtoc/src/jtoc_node.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/web-server.dir/build.make CMakeFiles/web-server.dir/srcs/libjtoc/src/jtoc_node.cpp.o
.PHONY : srcs/libjtoc/src/jtoc_node.cpp.o

srcs/libjtoc/src/jtoc_node.i: srcs/libjtoc/src/jtoc_node.cpp.i
.PHONY : srcs/libjtoc/src/jtoc_node.i

# target to preprocess a source file
srcs/libjtoc/src/jtoc_node.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/web-server.dir/build.make CMakeFiles/web-server.dir/srcs/libjtoc/src/jtoc_node.cpp.i
.PHONY : srcs/libjtoc/src/jtoc_node.cpp.i

srcs/libjtoc/src/jtoc_node.s: srcs/libjtoc/src/jtoc_node.cpp.s
.PHONY : srcs/libjtoc/src/jtoc_node.s

# target to generate assembly for a file
srcs/libjtoc/src/jtoc_node.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/web-server.dir/build.make CMakeFiles/web-server.dir/srcs/libjtoc/src/jtoc_node.cpp.s
.PHONY : srcs/libjtoc/src/jtoc_node.cpp.s

srcs/libjtoc/src/jtoc_parse.o: srcs/libjtoc/src/jtoc_parse.cpp.o
.PHONY : srcs/libjtoc/src/jtoc_parse.o

# target to build an object file
srcs/libjtoc/src/jtoc_parse.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/web-server.dir/build.make CMakeFiles/web-server.dir/srcs/libjtoc/src/jtoc_parse.cpp.o
.PHONY : srcs/libjtoc/src/jtoc_parse.cpp.o

srcs/libjtoc/src/jtoc_parse.i: srcs/libjtoc/src/jtoc_parse.cpp.i
.PHONY : srcs/libjtoc/src/jtoc_parse.i

# target to preprocess a source file
srcs/libjtoc/src/jtoc_parse.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/web-server.dir/build.make CMakeFiles/web-server.dir/srcs/libjtoc/src/jtoc_parse.cpp.i
.PHONY : srcs/libjtoc/src/jtoc_parse.cpp.i

srcs/libjtoc/src/jtoc_parse.s: srcs/libjtoc/src/jtoc_parse.cpp.s
.PHONY : srcs/libjtoc/src/jtoc_parse.s

# target to generate assembly for a file
srcs/libjtoc/src/jtoc_parse.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/web-server.dir/build.make CMakeFiles/web-server.dir/srcs/libjtoc/src/jtoc_parse.cpp.s
.PHONY : srcs/libjtoc/src/jtoc_parse.cpp.s

srcs/libjtoc/src/jtoc_parse_number.o: srcs/libjtoc/src/jtoc_parse_number.cpp.o
.PHONY : srcs/libjtoc/src/jtoc_parse_number.o

# target to build an object file
srcs/libjtoc/src/jtoc_parse_number.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/web-server.dir/build.make CMakeFiles/web-server.dir/srcs/libjtoc/src/jtoc_parse_number.cpp.o
.PHONY : srcs/libjtoc/src/jtoc_parse_number.cpp.o

srcs/libjtoc/src/jtoc_parse_number.i: srcs/libjtoc/src/jtoc_parse_number.cpp.i
.PHONY : srcs/libjtoc/src/jtoc_parse_number.i

# target to preprocess a source file
srcs/libjtoc/src/jtoc_parse_number.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/web-server.dir/build.make CMakeFiles/web-server.dir/srcs/libjtoc/src/jtoc_parse_number.cpp.i
.PHONY : srcs/libjtoc/src/jtoc_parse_number.cpp.i

srcs/libjtoc/src/jtoc_parse_number.s: srcs/libjtoc/src/jtoc_parse_number.cpp.s
.PHONY : srcs/libjtoc/src/jtoc_parse_number.s

# target to generate assembly for a file
srcs/libjtoc/src/jtoc_parse_number.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/web-server.dir/build.make CMakeFiles/web-server.dir/srcs/libjtoc/src/jtoc_parse_number.cpp.s
.PHONY : srcs/libjtoc/src/jtoc_parse_number.cpp.s

srcs/libjtoc/src/jtoc_parse_value.o: srcs/libjtoc/src/jtoc_parse_value.cpp.o
.PHONY : srcs/libjtoc/src/jtoc_parse_value.o

# target to build an object file
srcs/libjtoc/src/jtoc_parse_value.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/web-server.dir/build.make CMakeFiles/web-server.dir/srcs/libjtoc/src/jtoc_parse_value.cpp.o
.PHONY : srcs/libjtoc/src/jtoc_parse_value.cpp.o

srcs/libjtoc/src/jtoc_parse_value.i: srcs/libjtoc/src/jtoc_parse_value.cpp.i
.PHONY : srcs/libjtoc/src/jtoc_parse_value.i

# target to preprocess a source file
srcs/libjtoc/src/jtoc_parse_value.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/web-server.dir/build.make CMakeFiles/web-server.dir/srcs/libjtoc/src/jtoc_parse_value.cpp.i
.PHONY : srcs/libjtoc/src/jtoc_parse_value.cpp.i

srcs/libjtoc/src/jtoc_parse_value.s: srcs/libjtoc/src/jtoc_parse_value.cpp.s
.PHONY : srcs/libjtoc/src/jtoc_parse_value.s

# target to generate assembly for a file
srcs/libjtoc/src/jtoc_parse_value.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/web-server.dir/build.make CMakeFiles/web-server.dir/srcs/libjtoc/src/jtoc_parse_value.cpp.s
.PHONY : srcs/libjtoc/src/jtoc_parse_value.cpp.s

srcs/libjtoc/src/jtoc_read.o: srcs/libjtoc/src/jtoc_read.cpp.o
.PHONY : srcs/libjtoc/src/jtoc_read.o

# target to build an object file
srcs/libjtoc/src/jtoc_read.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/web-server.dir/build.make CMakeFiles/web-server.dir/srcs/libjtoc/src/jtoc_read.cpp.o
.PHONY : srcs/libjtoc/src/jtoc_read.cpp.o

srcs/libjtoc/src/jtoc_read.i: srcs/libjtoc/src/jtoc_read.cpp.i
.PHONY : srcs/libjtoc/src/jtoc_read.i

# target to preprocess a source file
srcs/libjtoc/src/jtoc_read.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/web-server.dir/build.make CMakeFiles/web-server.dir/srcs/libjtoc/src/jtoc_read.cpp.i
.PHONY : srcs/libjtoc/src/jtoc_read.cpp.i

srcs/libjtoc/src/jtoc_read.s: srcs/libjtoc/src/jtoc_read.cpp.s
.PHONY : srcs/libjtoc/src/jtoc_read.s

# target to generate assembly for a file
srcs/libjtoc/src/jtoc_read.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/web-server.dir/build.make CMakeFiles/web-server.dir/srcs/libjtoc/src/jtoc_read.cpp.s
.PHONY : srcs/libjtoc/src/jtoc_read.cpp.s

srcs/libjtoc/src/jtoc_read_file.o: srcs/libjtoc/src/jtoc_read_file.cpp.o
.PHONY : srcs/libjtoc/src/jtoc_read_file.o

# target to build an object file
srcs/libjtoc/src/jtoc_read_file.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/web-server.dir/build.make CMakeFiles/web-server.dir/srcs/libjtoc/src/jtoc_read_file.cpp.o
.PHONY : srcs/libjtoc/src/jtoc_read_file.cpp.o

srcs/libjtoc/src/jtoc_read_file.i: srcs/libjtoc/src/jtoc_read_file.cpp.i
.PHONY : srcs/libjtoc/src/jtoc_read_file.i

# target to preprocess a source file
srcs/libjtoc/src/jtoc_read_file.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/web-server.dir/build.make CMakeFiles/web-server.dir/srcs/libjtoc/src/jtoc_read_file.cpp.i
.PHONY : srcs/libjtoc/src/jtoc_read_file.cpp.i

srcs/libjtoc/src/jtoc_read_file.s: srcs/libjtoc/src/jtoc_read_file.cpp.s
.PHONY : srcs/libjtoc/src/jtoc_read_file.s

# target to generate assembly for a file
srcs/libjtoc/src/jtoc_read_file.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/web-server.dir/build.make CMakeFiles/web-server.dir/srcs/libjtoc/src/jtoc_read_file.cpp.s
.PHONY : srcs/libjtoc/src/jtoc_read_file.cpp.s

srcs/libjtoc/src/jtoc_utils.o: srcs/libjtoc/src/jtoc_utils.cpp.o
.PHONY : srcs/libjtoc/src/jtoc_utils.o

# target to build an object file
srcs/libjtoc/src/jtoc_utils.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/web-server.dir/build.make CMakeFiles/web-server.dir/srcs/libjtoc/src/jtoc_utils.cpp.o
.PHONY : srcs/libjtoc/src/jtoc_utils.cpp.o

srcs/libjtoc/src/jtoc_utils.i: srcs/libjtoc/src/jtoc_utils.cpp.i
.PHONY : srcs/libjtoc/src/jtoc_utils.i

# target to preprocess a source file
srcs/libjtoc/src/jtoc_utils.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/web-server.dir/build.make CMakeFiles/web-server.dir/srcs/libjtoc/src/jtoc_utils.cpp.i
.PHONY : srcs/libjtoc/src/jtoc_utils.cpp.i

srcs/libjtoc/src/jtoc_utils.s: srcs/libjtoc/src/jtoc_utils.cpp.s
.PHONY : srcs/libjtoc/src/jtoc_utils.s

# target to generate assembly for a file
srcs/libjtoc/src/jtoc_utils.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/web-server.dir/build.make CMakeFiles/web-server.dir/srcs/libjtoc/src/jtoc_utils.cpp.s
.PHONY : srcs/libjtoc/src/jtoc_utils.cpp.s

srcs/libjtoc/src/jtoc_utils2.o: srcs/libjtoc/src/jtoc_utils2.cpp.o
.PHONY : srcs/libjtoc/src/jtoc_utils2.o

# target to build an object file
srcs/libjtoc/src/jtoc_utils2.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/web-server.dir/build.make CMakeFiles/web-server.dir/srcs/libjtoc/src/jtoc_utils2.cpp.o
.PHONY : srcs/libjtoc/src/jtoc_utils2.cpp.o

srcs/libjtoc/src/jtoc_utils2.i: srcs/libjtoc/src/jtoc_utils2.cpp.i
.PHONY : srcs/libjtoc/src/jtoc_utils2.i

# target to preprocess a source file
srcs/libjtoc/src/jtoc_utils2.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/web-server.dir/build.make CMakeFiles/web-server.dir/srcs/libjtoc/src/jtoc_utils2.cpp.i
.PHONY : srcs/libjtoc/src/jtoc_utils2.cpp.i

srcs/libjtoc/src/jtoc_utils2.s: srcs/libjtoc/src/jtoc_utils2.cpp.s
.PHONY : srcs/libjtoc/src/jtoc_utils2.s

# target to generate assembly for a file
srcs/libjtoc/src/jtoc_utils2.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/web-server.dir/build.make CMakeFiles/web-server.dir/srcs/libjtoc/src/jtoc_utils2.cpp.s
.PHONY : srcs/libjtoc/src/jtoc_utils2.cpp.s

srcs/libjtoc/src/jtoc_validate.o: srcs/libjtoc/src/jtoc_validate.cpp.o
.PHONY : srcs/libjtoc/src/jtoc_validate.o

# target to build an object file
srcs/libjtoc/src/jtoc_validate.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/web-server.dir/build.make CMakeFiles/web-server.dir/srcs/libjtoc/src/jtoc_validate.cpp.o
.PHONY : srcs/libjtoc/src/jtoc_validate.cpp.o

srcs/libjtoc/src/jtoc_validate.i: srcs/libjtoc/src/jtoc_validate.cpp.i
.PHONY : srcs/libjtoc/src/jtoc_validate.i

# target to preprocess a source file
srcs/libjtoc/src/jtoc_validate.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/web-server.dir/build.make CMakeFiles/web-server.dir/srcs/libjtoc/src/jtoc_validate.cpp.i
.PHONY : srcs/libjtoc/src/jtoc_validate.cpp.i

srcs/libjtoc/src/jtoc_validate.s: srcs/libjtoc/src/jtoc_validate.cpp.s
.PHONY : srcs/libjtoc/src/jtoc_validate.s

# target to generate assembly for a file
srcs/libjtoc/src/jtoc_validate.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/web-server.dir/build.make CMakeFiles/web-server.dir/srcs/libjtoc/src/jtoc_validate.cpp.s
.PHONY : srcs/libjtoc/src/jtoc_validate.cpp.s

srcs/libjtoc/src/jtoc_validate_value.o: srcs/libjtoc/src/jtoc_validate_value.cpp.o
.PHONY : srcs/libjtoc/src/jtoc_validate_value.o

# target to build an object file
srcs/libjtoc/src/jtoc_validate_value.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/web-server.dir/build.make CMakeFiles/web-server.dir/srcs/libjtoc/src/jtoc_validate_value.cpp.o
.PHONY : srcs/libjtoc/src/jtoc_validate_value.cpp.o

srcs/libjtoc/src/jtoc_validate_value.i: srcs/libjtoc/src/jtoc_validate_value.cpp.i
.PHONY : srcs/libjtoc/src/jtoc_validate_value.i

# target to preprocess a source file
srcs/libjtoc/src/jtoc_validate_value.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/web-server.dir/build.make CMakeFiles/web-server.dir/srcs/libjtoc/src/jtoc_validate_value.cpp.i
.PHONY : srcs/libjtoc/src/jtoc_validate_value.cpp.i

srcs/libjtoc/src/jtoc_validate_value.s: srcs/libjtoc/src/jtoc_validate_value.cpp.s
.PHONY : srcs/libjtoc/src/jtoc_validate_value.s

# target to generate assembly for a file
srcs/libjtoc/src/jtoc_validate_value.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/web-server.dir/build.make CMakeFiles/web-server.dir/srcs/libjtoc/src/jtoc_validate_value.cpp.s
.PHONY : srcs/libjtoc/src/jtoc_validate_value.cpp.s

srcs/libjtoc/src/jtoc_write.o: srcs/libjtoc/src/jtoc_write.cpp.o
.PHONY : srcs/libjtoc/src/jtoc_write.o

# target to build an object file
srcs/libjtoc/src/jtoc_write.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/web-server.dir/build.make CMakeFiles/web-server.dir/srcs/libjtoc/src/jtoc_write.cpp.o
.PHONY : srcs/libjtoc/src/jtoc_write.cpp.o

srcs/libjtoc/src/jtoc_write.i: srcs/libjtoc/src/jtoc_write.cpp.i
.PHONY : srcs/libjtoc/src/jtoc_write.i

# target to preprocess a source file
srcs/libjtoc/src/jtoc_write.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/web-server.dir/build.make CMakeFiles/web-server.dir/srcs/libjtoc/src/jtoc_write.cpp.i
.PHONY : srcs/libjtoc/src/jtoc_write.cpp.i

srcs/libjtoc/src/jtoc_write.s: srcs/libjtoc/src/jtoc_write.cpp.s
.PHONY : srcs/libjtoc/src/jtoc_write.s

# target to generate assembly for a file
srcs/libjtoc/src/jtoc_write.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/web-server.dir/build.make CMakeFiles/web-server.dir/srcs/libjtoc/src/jtoc_write.cpp.s
.PHONY : srcs/libjtoc/src/jtoc_write.cpp.s

srcs/main.o: srcs/main.cpp.o
.PHONY : srcs/main.o

# target to build an object file
srcs/main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/web-server.dir/build.make CMakeFiles/web-server.dir/srcs/main.cpp.o
.PHONY : srcs/main.cpp.o

srcs/main.i: srcs/main.cpp.i
.PHONY : srcs/main.i

# target to preprocess a source file
srcs/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/web-server.dir/build.make CMakeFiles/web-server.dir/srcs/main.cpp.i
.PHONY : srcs/main.cpp.i

srcs/main.s: srcs/main.cpp.s
.PHONY : srcs/main.s

# target to generate assembly for a file
srcs/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/web-server.dir/build.make CMakeFiles/web-server.dir/srcs/main.cpp.s
.PHONY : srcs/main.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... web-server"
	@echo "... srcs/cgi/SingleCgiHandler.o"
	@echo "... srcs/cgi/SingleCgiHandler.i"
	@echo "... srcs/cgi/SingleCgiHandler.s"
	@echo "... srcs/config/Config.o"
	@echo "... srcs/config/Config.i"
	@echo "... srcs/config/Config.s"
	@echo "... srcs/core/events/Event.o"
	@echo "... srcs/core/events/Event.i"
	@echo "... srcs/core/events/Event.s"
	@echo "... srcs/core/events/EventPresets.o"
	@echo "... srcs/core/events/EventPresets.i"
	@echo "... srcs/core/events/EventPresets.s"
	@echo "... srcs/core/modules/EpollModule.o"
	@echo "... srcs/core/modules/EpollModule.i"
	@echo "... srcs/core/modules/EpollModule.s"
	@echo "... srcs/core/modules/PollModule.o"
	@echo "... srcs/core/modules/PollModule.i"
	@echo "... srcs/core/modules/PollModule.s"
	@echo "... srcs/http/HttpModule.o"
	@echo "... srcs/http/HttpModule.i"
	@echo "... srcs/http/HttpModule.s"
	@echo "... srcs/http/Request.o"
	@echo "... srcs/http/Request.i"
	@echo "... srcs/http/Request.s"
	@echo "... srcs/http/Response.o"
	@echo "... srcs/http/Response.i"
	@echo "... srcs/http/Response.s"
	@echo "... srcs/libjtoc/src/ft_atoi.o"
	@echo "... srcs/libjtoc/src/ft_atoi.i"
	@echo "... srcs/libjtoc/src/ft_atoi.s"
	@echo "... srcs/libjtoc/src/ft_bzero.o"
	@echo "... srcs/libjtoc/src/ft_bzero.i"
	@echo "... srcs/libjtoc/src/ft_bzero.s"
	@echo "... srcs/libjtoc/src/ft_isdigit.o"
	@echo "... srcs/libjtoc/src/ft_isdigit.i"
	@echo "... srcs/libjtoc/src/ft_isdigit.s"
	@echo "... srcs/libjtoc/src/ft_itoa.o"
	@echo "... srcs/libjtoc/src/ft_itoa.i"
	@echo "... srcs/libjtoc/src/ft_itoa.s"
	@echo "... srcs/libjtoc/src/ft_memalloc.o"
	@echo "... srcs/libjtoc/src/ft_memalloc.i"
	@echo "... srcs/libjtoc/src/ft_memalloc.s"
	@echo "... srcs/libjtoc/src/ft_memcpy.o"
	@echo "... srcs/libjtoc/src/ft_memcpy.i"
	@echo "... srcs/libjtoc/src/ft_memcpy.s"
	@echo "... srcs/libjtoc/src/ft_strcpy.o"
	@echo "... srcs/libjtoc/src/ft_strcpy.i"
	@echo "... srcs/libjtoc/src/ft_strcpy.s"
	@echo "... srcs/libjtoc/src/ft_strdup.o"
	@echo "... srcs/libjtoc/src/ft_strdup.i"
	@echo "... srcs/libjtoc/src/ft_strdup.s"
	@echo "... srcs/libjtoc/src/ft_strhash.o"
	@echo "... srcs/libjtoc/src/ft_strhash.i"
	@echo "... srcs/libjtoc/src/ft_strhash.s"
	@echo "... srcs/libjtoc/src/ft_strlen.o"
	@echo "... srcs/libjtoc/src/ft_strlen.i"
	@echo "... srcs/libjtoc/src/ft_strlen.s"
	@echo "... srcs/libjtoc/src/ft_strncmp.o"
	@echo "... srcs/libjtoc/src/ft_strncmp.i"
	@echo "... srcs/libjtoc/src/ft_strncmp.s"
	@echo "... srcs/libjtoc/src/ft_strnew.o"
	@echo "... srcs/libjtoc/src/ft_strnew.i"
	@echo "... srcs/libjtoc/src/ft_strnew.s"
	@echo "... srcs/libjtoc/src/ft_strsub.o"
	@echo "... srcs/libjtoc/src/ft_strsub.i"
	@echo "... srcs/libjtoc/src/ft_strsub.s"
	@echo "... srcs/libjtoc/src/jtoc_get.o"
	@echo "... srcs/libjtoc/src/jtoc_get.i"
	@echo "... srcs/libjtoc/src/jtoc_get.s"
	@echo "... srcs/libjtoc/src/jtoc_get_raw_data.o"
	@echo "... srcs/libjtoc/src/jtoc_get_raw_data.i"
	@echo "... srcs/libjtoc/src/jtoc_get_raw_data.s"
	@echo "... srcs/libjtoc/src/jtoc_node.o"
	@echo "... srcs/libjtoc/src/jtoc_node.i"
	@echo "... srcs/libjtoc/src/jtoc_node.s"
	@echo "... srcs/libjtoc/src/jtoc_parse.o"
	@echo "... srcs/libjtoc/src/jtoc_parse.i"
	@echo "... srcs/libjtoc/src/jtoc_parse.s"
	@echo "... srcs/libjtoc/src/jtoc_parse_number.o"
	@echo "... srcs/libjtoc/src/jtoc_parse_number.i"
	@echo "... srcs/libjtoc/src/jtoc_parse_number.s"
	@echo "... srcs/libjtoc/src/jtoc_parse_value.o"
	@echo "... srcs/libjtoc/src/jtoc_parse_value.i"
	@echo "... srcs/libjtoc/src/jtoc_parse_value.s"
	@echo "... srcs/libjtoc/src/jtoc_read.o"
	@echo "... srcs/libjtoc/src/jtoc_read.i"
	@echo "... srcs/libjtoc/src/jtoc_read.s"
	@echo "... srcs/libjtoc/src/jtoc_read_file.o"
	@echo "... srcs/libjtoc/src/jtoc_read_file.i"
	@echo "... srcs/libjtoc/src/jtoc_read_file.s"
	@echo "... srcs/libjtoc/src/jtoc_utils.o"
	@echo "... srcs/libjtoc/src/jtoc_utils.i"
	@echo "... srcs/libjtoc/src/jtoc_utils.s"
	@echo "... srcs/libjtoc/src/jtoc_utils2.o"
	@echo "... srcs/libjtoc/src/jtoc_utils2.i"
	@echo "... srcs/libjtoc/src/jtoc_utils2.s"
	@echo "... srcs/libjtoc/src/jtoc_validate.o"
	@echo "... srcs/libjtoc/src/jtoc_validate.i"
	@echo "... srcs/libjtoc/src/jtoc_validate.s"
	@echo "... srcs/libjtoc/src/jtoc_validate_value.o"
	@echo "... srcs/libjtoc/src/jtoc_validate_value.i"
	@echo "... srcs/libjtoc/src/jtoc_validate_value.s"
	@echo "... srcs/libjtoc/src/jtoc_write.o"
	@echo "... srcs/libjtoc/src/jtoc_write.i"
	@echo "... srcs/libjtoc/src/jtoc_write.s"
	@echo "... srcs/main.o"
	@echo "... srcs/main.i"
	@echo "... srcs/main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

